# Generated by Django 4.0.5 on 2022-07-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agencia', '0002_remove_tipopqrs_fechacreado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('idTipoParentesco', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('idIntegrante', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('NumeroDocumento', models.IntegerField()),
                ('FechaCreado', models.DateTimeField(auto_now_add=True)),
                ('FechaNacimiento', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.cliente')),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.tipodocumento')),
                ('idTipoParentesco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agencia.tipoparentesco')),
            ],
        ),
    ]
