# Generated by Django 4.0.4 on 2022-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agencia', '0004_cliente_password_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
